### PR TITLE
Fix

### LINKED ISSUE #16: Serious CSS redesigning
I mean come on, I need to say more? More people will see the website to use it rather than to contribute. So remove the "See our license" thing and take them straight to the pages.

I will help with this, Also, the black background is BORING. we should use something like in JS tutorials.

Also, sharp corners make websites professional. So no rounded corners.

- [x] No Sharp corners 
- [x] Change Background
- [x] REMOVE THE FIRST PAGE

### PR DESCRIPTION
**Pull request by Genius398**
fixes #16 sorta

### CODE REVIEW

**Comment by Super45coder** [comment]
We cannot do this. We can try to fix the issue, or I will change the page so that there is only a button. We need this page so that the reader will follow the rules. Sorry.

**Comment by Super45coder** [comment]
@Genius398 There are problems with merging. Can you make another pull request?

**Comment by Genius398** [comment]
> We cannot do this. We can try to fix the issue, or I will change the page so that there is only a button. We need this page so that the reader will follow the rules. Sorry.

the "rules" are useless unless the user wants to contribute

**Comment by Super45coder** [comment]
Good point. Can you make another pull request? Problem with the other.
________________________________

**Comment by Genius398** [comment]
Ok

**Comment by somePythonProgrammer** [comment]
> We cannot do this. We can try to fix the issue, or I will change the page so that there is only a button. We need this page so that the reader will follow the rules. Sorry.

I think that keeping a button is better.

**Comment by Super45coder** [comment]
Okay
________________________________

**Comment by Genius398** [comment]
> > We cannot do this. We can try to fix the issue, or I will change the page so that there is only a button. We need this page so that the reader will follow the rules. Sorry.
> 
> I think that keeping a button is better.

Ya. buttons with good styling are extremely user friendly

**Pull request closed without merging**
