### PR TITLE
fix something weird on the README

### PR DESCRIPTION
**Pull request by somePythonProgrammer**
just an annoying mistake!

### CODE REVIEW

**Comment by somePythonProgrammer** [comment]
@Super45coder Please add me to this org and to this repo.

**Comment by Genius398** [comment]
@Super45coder ADD US!

**Comment by somePythonProgrammer** [comment]
@Super45coder @Super45coder @Super45coder !

**Comment by Super45coder** [comment]
Sorry. I was offline. Yes, I will invite you.

**Comment by somePythonProgrammer** [comment]
Thanks!

**Comment by Super45coder** [comment]
I am in denver. I was sleeping.
________________________________

**Comment by somePythonProgrammer** [comment]
Oh. No problem. I forgot that there are different time zones.
[;)]

**Comment by Super45coder** [comment]
Yeah.
________________________________

**Comment by Genius398** [comment]
😆

**Pull request merged**
